# Generated by Django 2.1 on 2019-05-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_vendor', models.CharField(max_length=30)),
                ('product_price', models.IntegerField()),
                ('product_qty', models.IntegerField()),
                ('product_descr', models.CharField(max_length=30)),
                ('product_labal', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'product_info',
            },
        ),
    ]
