# Generated by Django 2.1 on 2019-06-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customer_waiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='waiter',
            field=models.ManyToManyField(to='myapp.Waiter'),
        ),
    ]
